@isTest
private class Test_MetadataService_V1 {
    static testMethod void myTest(){
        MetadataService_V1 metadataSrvc = new MetadataService_V1();
        MetadataService_V1.SessionHeader_element sessHeader = new MetadataService_V1.SessionHeader_element();
        MetadataService_V1.DebuggingInfo_element debugLogg = new MetadataService_V1.DebuggingInfo_element();
        MetadataService_V1.CallOptions_element callOptions = new MetadataService_V1.CallOptions_element();
        MetadataService_V1.DescribeMetadataResult descRslt = new MetadataService_V1.DescribeMetadataResult();
        MetadataService_V1.DescribeMetadataObject descObj = new MetadataService_V1.DescribeMetadataObject();
        MetadataService_V1.describeMetadata_element descMetadata = new MetadataService_V1.describeMetadata_element();
        MetadataService_V1.describeMetadataResponse_element descRes = new MetadataService_V1.describeMetadataResponse_element();
        MetadataService_V1.ListMetadataQuery listQuery = new MetadataService_V1.ListMetadataQuery();
        MetadataService_V1.FileProperties fileProp = new MetadataService_V1.FileProperties();
        MetadataService_V1.listMetadata_element listMetadata = new MetadataService_V1.listMetadata_element();
        MetadataService_V1.listMetadataResponse_element listMetadataRes = new MetadataService_V1.listMetadataResponse_element();
        MetadataService_V1.DebuggingHeader_element dibugHeader = new MetadataService_V1.DebuggingHeader_element();
        MetadataService_V1.LogInfo logInfo = new MetadataService_V1.LogInfo();
        MetadataService_V1.RemoteSiteSetting remoteSettng = new MetadataService_V1.RemoteSiteSetting();
        MetadataService_V1.ReadResult ReadResult = new MetadataService_V1.ReadResult();
        MetadataService_V1.Metadata metadata = new MetadataService_V1.Metadata();
        MetadataService_V1.SaveResult saveResult = new MetadataService_V1.SaveResult();
        MetadataService_V1.Error error = new MetadataService_V1.Error();
        
    }
}